// app/terms/page.tsx
"use client";

export default function TermsPage() {
  return (
    <main className="max-w-3xl mx-auto px-6 py-12 text-left leading-relaxed">
      <h1 className="text-3xl font-bold mb-6">Greanly — Terms of Use & Disclaimer</h1>

      <p className="mb-4">
        These Terms of Use govern your access to and use of <strong>Greanly</strong>
        (“AI Assistant”, “we”, “us”, “our”). By using Greanly, you agree to these terms.
        If you do not agree, you may not use the service.
      </p>

      <h2 className="text-xl font-semibold mt-8 mb-3">1. Purpose of Greanly</h2>
      <p className="mb-4">
        Greanly is an AI-powered assistant designed to help individuals and businesses with:
      </p>
      <ul className="list-disc ml-6 mb-4">
        <li>Sustainability questions & learning</li>
        <li>Cost-saving and waste-reduction insights</li>
        <li>Supplier/material discovery</li>
        <li>Simple 30/60/90-day sustainability action plans</li>
      </ul>
      <p className="mb-4">
        Greanly is <strong>not</strong> a legally certified consultant, auditor, or professional advisor.
        All responses are general guidance only.
      </p>

      <h2 className="text-xl font-semibold mt-8 mb-3">2. Country of Operation</h2>
      <p className="mb-4">
        Greanly is developed and operated from <strong>India</strong>. All data processing, business
        operations, and compliance follow applicable laws of India unless otherwise stated.
      </p>

      <h2 className="text-xl font-semibold mt-8 mb-3">3. No Guarantee of Accuracy</h2>
      <p className="mb-4">
        Greanly uses artificial intelligence to generate responses. While we aim for accuracy and
        quality, the AI may produce incomplete, outdated, or incorrect information. Users must
        independently verify any suggestion before implementing it, especially for business or
        compliance purposes.
      </p>

      <h2 className="text-xl font-semibold mt-8 mb-3">4. Third-Party Services & Data Processing</h2>
      <p className="mb-4">
        Greanly relies on third-party AI providers, APIs, analytics tools, and hosting partners.
        Your inputs may be processed or stored on servers located outside India. We do not control
        or guarantee the security policies of these providers.
      </p>
      <p className="mb-4">
        <strong>Confidentiality cannot be guaranteed.</strong> Do not share sensitive, personal,
        financial, or proprietary information with the chatbot.
      </p>

      <h2 className="text-xl font-semibold mt-8 mb-3">5. User Responsibilities</h2>
      <p className="mb-4">By using Greanly, you agree that you will not:</p>
      <ul className="list-disc ml-6 mb-4">
        <li>Share harmful, illegal, offensive, or discriminatory content</li>
        <li>Use Greanly for any unlawful, unethical, or malicious purpose</li>
        <li>Attempt to hack, disrupt, or reverse-engineer the system</li>
        <li>Use Greanly to generate misinformation or harmful outputs</li>
      </ul>

      <h2 className="text-xl font-semibold mt-8 mb-3">6. Ownership of Content</h2>
      <p className="mb-4">
        All inputs you provide and all outputs generated by Greanly may be stored, analysed,
        and used for improving the service, research, or product development.
      </p>
      <p className="mb-4">
        You agree that you have no ownership rights over AI-generated content and grant us the
        right to use your inputs for model improvement, analytics, and future features.
      </p>

      <h2 className="text-xl font-semibold mt-8 mb-3">7. Liability Limitations</h2>
      <p className="mb-4">
        Greanly is provided on an <strong>"as-is" and "as-available"</strong> basis. We make no
        warranties—express or implied—regarding:
      </p>
      <ul className="list-disc ml-6 mb-4">
        <li>Accuracy of information</li>
        <li>Availability or reliability of the service</li>
        <li>Suitability of suggestions for business decisions</li>
      </ul>
      <p className="mb-4">
        To the fullest extent allowed by Indian law, Greanly and its creators are not liable
        for any loss, damages, costs, or claims arising from your use of the service.
      </p>

      <h2 className="text-xl font-semibold mt-8 mb-3">8. Fees and Modifications</h2>
      <p className="mb-4">
        Greanly is currently free. We may introduce paid features or modify the service at any
        time without notice.
      </p>

      <h2 className="text-xl font-semibold mt-8 mb-3">9. Governing Law</h2>
      <p className="mb-4">
        These Terms are governed by the laws of <strong>India</strong>. Any disputes will fall under
        the jurisdiction of courts located in <strong>New Delhi, India</strong>.
      </p>

      <h2 className="text-xl font-semibold mt-8 mb-3">10. Acceptance of Terms</h2>
      <p className="mb-8">
        By using Greanly, you confirm that you have read, understood, and agreed to these
        Terms of Use. If you do not agree, please discontinue use.
      </p>

      <p className="text-sm text-muted-foreground">Last Updated: November 2025</p>
    </main>
  );
}
